version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "9090:9090"
    depends_on:
      - mongodb
      - redis
      - rabbitmq

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data: